name: Build multi-architecture images

on:
  push:
    branches:
      - main
    tags:        
      - v*

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_PASSWORD }}
      - name: Build and Push GHCR Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ github.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          push: true # Will only build if this is not here
          tags: |
            ${{ github.repository }}:${{ github.ref }}
            ${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64