name: Build multi-architecture images

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push to docker hub
        run: |
          docker buildx build --push \
            --tag richardsoper/discord-role-bot:latest \
            --platform linux/amd64,linux/arm64 . 
      - name: login to ghcr
        run: echo "${{ secrets.GITHUB_PASSWORD }}" | docker login ghcr.io -u "${{ secrets.GITHUB_USERNAME }}" --password-stdin
      - name: build and push to ghcr
        run: |
          docker buildx build --push \
            --tag ghcr.io/rsoper/discord-role-bot:latest \
            --platform linux/amd64,linux/arm64 .
